CREATE TABLE [dbo].[SUPPLIER] (
    [SID]    CHAR (5)     NOT NULL,
    [SNAME]  VARCHAR (50) NULL,
    [SADD]   VARCHAR (50) NULL,
    [SCITY]  VARCHAR (20) CONSTRAINT [city_delhi] DEFAULT ('DELHI') NULL,
    [SPHONE] VARCHAR (20) NULL,
    [EMAIL]  VARCHAR (30) NULL,
    CONSTRAINT [sid_primary] PRIMARY KEY CLUSTERED ([SID] ASC),
    CONSTRAINT [unique_sphone] UNIQUE NONCLUSTERED ([SPHONE] ASC)
);


GO

